modLoader="javafml"
loaderVersion="[4,)"
license="${mod_license}"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''
[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="ae2"
type="optional"
versionRange="[19.2.17,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="beyonddimensions"
type="optional"
versionRange="[0.7.26,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="refinedstorage"
type="optional"
versionRange="[2.0.9,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="refinedstorage_quartz_arsenal"
type="optional"
versionRange="[1.0.8,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="refinedstorage_curios_integration"
type="optional"
versionRange="[1.0.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="sophisticatedbackpacks"
type="optional"
versionRange="[3.25.34,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="projecte"
type="optional"
versionRange="[1.1.0,)"
ordering="AFTER"
side="BOTH"
