modLoader="javafml"
loaderVersion="[4,)"
license="${mod_license}"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''
[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[26.1.2,)"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="[26.1.2,26.2)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="ae2"
type="optional"
versionRange="[26.1.10-beta,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="beyonddimensions"
type="optional"
versionRange="[0.7.27,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="refinedstorage"
type="optional"
versionRange="[3.2.1,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="refinedstorage_quartz_arsenal"
type="optional"
versionRange="[2.0.6,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="refinedstorage_curios_integration"
type="optional"
versionRange="[2.0.1,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="sophisticatedbackpacks"
type="optional"
versionRange="[3.25.86,)"
ordering="AFTER"
side="BOTH"
